### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by petrasovaa** [Biosystems-Analytics-Lab/shellcast#1]
Since this is supposed to be open source, please include license to make that clearer. Thanks!

**Comment by sheilasaia** [comment]
Thanks for reaching out, @petrasovaa! The license file is in the doc folder as described in the main repository [readme see section 3 "documentation overview"](https://github.com/Biosystems-Analytics-Lab/shellcast). Specifically, you can find it [here](https://github.com/Biosystems-Analytics-Lab/shellcast/blob/master/docs/LICENSE.md)

**Comment by petrasovaa** [comment]
Thanks! Not sure what went into the decisions which license to pick, but just in case you haven't seen that before:
https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

I ran into your new PLOS paper, so I was curious to see this project, nice job!

**Comment by sheilasaia** [comment]
@petrasovaa, thanks for sharing that link and I'm glad you found our PLOS paper! 😄  Yes, it was a difficult decision that we tried to consult with the libraries about. In the end we settled for CCby because this is familiar to us and prioritizes how we are evaluated as researchers (i.e., by our citations). I'm going to ping @nataliegnelson so she's aware and can change it if she wishes!
